build:
  maxIssues: 0

config:
  validation: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'

complexity:
  LongMethod:
    threshold: 70
  TooManyFunctions:
    thresholdInFiles: 12
    thresholdInClasses: 10
    thresholdInObjects: 10
    thresholdInInterfaces: 10
    thresholdInEnums: 10
